name: Build and deploy ASP.Net Core app to Azure Web App - web-auea-nprd-sit-tempus-01

on:
  push:
    branches:
      - main  # Specify 'main' as the branch name
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: [self-hosted, windows, x64]  # Ensure you're using a self-hosted runner

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4  

      # Set up .NET Core with custom installation path
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'
          installation-path: 'D:\R D Skill\actions-runner\dotnet'  # Install .NET to this custom directory

      # Verify .NET SDK installation
      - name: Verify .NET installation
        run: dotnet --version

      # Build the application
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the application
      - name: Publish the application
        run: |
          dotnet publish -c Release -o "${{ github.workspace }}/myapp"
          
      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: "${{ github.workspace }}/myapp"

  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner for deployment job
    needs: build  # Ensure deployment only happens after the build job

    environment:
      name: 'Production'  # Target environment (can be modified based on your needs)

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app  

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3 
        with:
          app-name: 'web-auea-nprd-sit-tempus-01'  # Your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Azure Publish Profile stored in GitHub secrets
          package: .  # Deploy the package created in the build job
