name: Build and deploy ASP.Net Core app to Azure Web App - web-auea-nprd-sit-tempus-01

on:
  push:
    branches:
      - master  # Specify branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      # Checkout the code
      - uses: actions/checkout@v4  

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'

      # Build the application
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the application
      - name: Publish the application
        run: |
          dotnet publish -c Release -o "${{ github.workspace }}/myapp"
      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: "${{ github.workspace }}/myapp"

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    environment:
      name: 'Production'

    steps:
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app  

      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3 
        with:
          app-name: 'web-auea-nprd-sit-tempus-01' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST1234 }}
          package: .
